const args: Array<string> = Deno.args;
// Decoder & Encoder zum Lesen und Schreiben anlegen
const decoder = new TextDecoder("utf-8");
const encoder = new TextEncoder();
const data = encoder.encode("Autogenerated File by our Deno-Program\n");

args.forEach((el) => {
  let found = false;
  // Für alle Entrys im Ordner prüfen ob Datei gleich des args
  for (const dirEntry of Deno.readDirSync("./")) {
    if (dirEntry.name === el) {
      // Wenn Ja ausgeben der Datei
      console.log("Datei " + el + " mit folgendem Inhalt gefunden:");
      console.log(decoder.decode(Deno.readFileSync(el)));
      found = true;
    }
  }
  if (!found) {
    // Datei wurde nicht gefunden muss also angelegt werden
    Deno.writeFileSync(el, data);
  }
});
